version: 2

models:
  - name: d_market_data
    description: market data pour les backtests à intégrer

  - name: d_backtest
    description: informations sur les backtests joués

  - name: d_strategy_param
    description: paramètres utilisés pour un backtest

  - name: d_order
    description: tous les ordres des backtest

  - name: d_position
    description: toutes les positions des backtest