CREATE TABLE IF NOT EXISTS PORTFOLIO (
    TRADING_SESSION_ID INT,
    PORTFOLIO_EVENT_TIMESTAMP INT,
    PORTFOLIO_EVENT_TYPE VARCHAR(100),
    CASH_BALANCE DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP
);