CREATE TABLE IF NOT EXISTS MARKET_DATA (
    OPEN_TIMESTAMP INT,
    OPEN DECIMAL(30,15),
    HIGH DECIMAL(30,15),
    LOW DECIMAL(30,15),
    CLOSE DECIMAL(30,15),
    CLOSE_TIME INT,
    QUOTE_ASSET_VOLUME DECIMAL(30,15),
    NUMBER_OF_TRADES INT,
    TAKER_BUY_BASE_ASSET_VOLUME DECIMAL(30,15),
    TAKER_BUY_QUOTE_ASSET_VOLUME DECIMAL(30,15),
    CONSTRAINT MARKET_DATA_PK PRIMARY KEY (OPEN_TIME)
);