tb_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.21.0.3
      user: LeRequeteur
      password: LenulAlex
      port: 5432
      dbname: GTBDD
      schema: dmbtc
      threads: 4