CREATE TABLE IF NOT EXISTS DMBTE.E_PORTFOLIO (
    BACKTEST_ID CHAR(64),
    PORTFOLIO_EVENT_TIMESTAMP INT,
    PORTFOLIO_EVENT_TYPE VARCHAR(100),
    CASH_BALANCE DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP
);
