CREATE TABLE IF NOT EXISTS DMBTC.C_ORDER (
    BACKTEST_ID CHAR(64),
    ORDER_ID INT,
    ORDER_EVENT_TIMESTAMP TIMESTAMP,
    ORDER_EVENT_TYPE VARCHAR(30),
    ORDER_SIDE VARCHAR(5),
    ORDER_LEVEL DECIMAL(30,15),
    ORDER_ASSET_QTY DECIMAL(30,15),
    ORDER_LEVERAGE DECIMAL(4,1),
    ORDER_TAKE_PROFIT_PRICE DECIMAL(30,15),
    ORDER_STOP_LOSS_PRICE DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP,
    CONSTRAINT ORDER_PK PRIMARY KEY (BACKTEST_ID, ORDER_ID, ORDER_EVENT_TIMESTAMP, ORDER_EVENT_TYPE)
);