CREATE TABLE IF NOT EXISTS DMBTE.E_BACKTEST (
    BACKTEST_ID CHAR(64),
    BACKTEST_HISTORICAL_START_TIMESTAMP TIMESTAMP,
    BACKTEST_HISTORICAL_END_TIMESTAMP TIMESTAMP,
    SYMBOL VARCHAR(20),
    STRATEGY_NAME VARCHAR(100),
    STRATEGY_TYPE VARCHAR(100),
    --STRATEGY_PARAMS JSON,
    INITIAL_MONEY DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP,
    CONSTRAINT BACKTEST_PK PRIMARY KEY (BACKTEST_ID)
);
