CREATE TABLE IF NOT EXISTS DMBTE.E_POSITION (
    BACKTEST_ID CHAR(64),
    POSITION_ID INT,
    ORDER_ID INT,
    POSITION_EVENT_TIMESTAMP TIMESTAMP,
    POSITION_EVENT_TYPE VARCHAR(100),
    POSITION_SIDE VARCHAR(100),
    POSITION_MARGIN DECIMAL(30,15),
    POSITION_ENTRY_PRICE DECIMAL(30,15),
    POSITION_ASSET_QTY DECIMAL(30,15),
    POSITION_LEVERAGE DECIMAL(4,1),
    POSITION_TAKE_PROFIT_PRICE DECIMAL(30,15),
    POSITION_STOP_LOSS_PRICE DECIMAL(30,15),
    POSITION_CLOSE_PRICE DECIMAL(30,15),
    POSITION_CLOSE_TYPE VARCHAR(100),
    OPERATIONAL_TIMESTAMP TIMESTAMP,
    CONSTRAINT POSITION_PK PRIMARY KEY (BACKTEST_ID, POSITION_ID, POSITION_EVENT_TIMESTAMP, POSITION_EVENT_TYPE)
);
