CREATE TABLE IF NOT EXISTS DMBTE.E_STRATEGY_PARAM (
    TRADING_SESSION_ID INT,
    PARAM_NAME VARCHAR(100),
    PARAM_VALUE VARCHAR(100),
    CONSTRAINT STRATEGY_PARAM_PK PRIMARY KEY (TRADING_SESSION_ID, PARAM_NAME)
);