CREATE TABLE IF NOT EXISTS E_ORDER (
    TRADING_SESSION_ID INT,
    ORDER_ID INT,
    ORDER_EVENT_TIMESTAMP INT,
    ORDER_EVENT_TYPE VARCHAR(100),
    ORDER_SIDE VARCHAR(100),
    ORDER_LEVEL DECIMAL(30,15),
    ORDER_ASSET_QTY DECIMAL(30,15),
    ORDER_LEVERAGE DECIMAL(4,1),
    ORDER_TAKE_PROFIT_PRICE DECIMAL(30,15),
    ORDER_STOP_LOSS_PRICE DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP,
    CONSTRAINT ORDER_PK PRIMARY KEY (TRADING_SESSION_ID, ORDER_ID, ORDER_EVENT_TIMESTAMP, ORDER_EVENT_TYPE)
);