CREATE TABLE IF NOT EXISTS E_TRADING_SESSION (
    TRADING_SESSION_ID INT,
    TRADING_SESSION_TYPE VARCHAR(100),
    TRADING_SESSION_HISTORICAL_START_TIMESTAMP INT,
    TRADING_SESSION_HISTORICAL_END_TIMESTAMP INT,
    SYMBOL VARCHAR(20),
    STRATEGY_NAME VARCHAR(100),
    STRATEGY_TYPE VARCHAR(100),
    STRATEGY_PARAMS JSON,
    INITIAL_MONEY DECIMAL(30,15),
    OPERATIONAL_TIMESTAMP TIMESTAMP,
    CONSTRAINT TRADING_SESSION_PK PRIMARY KEY (TRADING_SESSION_ID)
);
