CREATE TABLE IF NOT EXISTS DMBTD.D_STRATEGY_PARAM (
    BACKTEST_ID CHAR(64),
    PARAM_ID INT,
    PARAM_NAME VARCHAR(100),
    PARAM_VALUE VARCHAR(100),
    CONSTRAINT STRATEGY_PARAM_PK PRIMARY KEY (BACKTEST_ID, PARAM_NAME)
);