CREATE TABLE IF NOT EXISTS DMBTD.D_MARKET_DATA (
    SYMBOL VARCHAR(10),
    OPEN_TIME BIGINT,
    OPEN DECIMAL(30,15),
    HIGH DECIMAL(30,15),
    LOW DECIMAL(30,15),
    CLOSE DECIMAL(30,15),
    VOLUME DECIMAL(30,15),
    CLOSE_TIME BIGINT,
    QUOTE_ASSET_VOLUME DECIMAL(30,15),
    NUMBER_OF_TRADES BIGINT,
    TAKER_BUY_BASE_ASSET_VOLUME DECIMAL(30,15),
    TAKER_BUY_QUOTE_ASSET_VOLUME DECIMAL(30,15),
    CONSTRAINT MARKET_DATA_PK PRIMARY KEY (SYMBOL, OPEN_TIME)
);